language: csharp
solution: GraphBLAS-sharp.sln
mono: none
dotnet: 3.1

env:
  global:
    - OMP_NUM_THREADS=4
    - AMDAPPSDKROOT=/opt/intel/opencl/

dist: bionic
addons:
  apt:
    packages:
    - clinfo
    - pocl

# before_install:
#   - bash .travis/install_intel_opencl.sh

install:
  - dotnet tool restore
  - dotnet paket restore

script:
  - clinfo
  - dotnet test